export type Template = {
  id: number
  title: string
  content: string
  language: string
  template_type: string
  tags: string[]
  type: "sms" | "email"
  subject?: string
}

export const templates: Template[] = [
  // SMS Templates
  {
    id: 1,
    title: "OTP Verification",
    content: "Your OTP is {{otp}}, valid for 5 minutes.",
    language: "en",
    template_type: "security",
    tags: ["otp", "security", "login"],
    type: "sms",
  },
  {
    id: 2,
    title: "Account Activation",
    content: "Welcome to {{app_name}}! Use code {{activation_code}} to activate your account.",
    language: "en",
    template_type: "security",
    tags: ["activation", "account", "security"],
    type: "sms",
  },
  {
    id: 3,
    title: "Password Reset",
    content: "You requested a password reset. Use code {{reset_code}} to change your password.",
    language: "en",
    template_type: "security",
    tags: ["reset", "password", "security"],
    type: "sms",
  },
  {
    id: 4,
    title: "Payment Confirmation",
    content: "Thank you for your payment of {{amount}}. Your transaction ID is {{transaction_id}}.",
    language: "en",
    template_type: "transactional",
    tags: ["payment", "transaction", "confirmation"],
    type: "sms",
  },
  {
    id: 5,
    title: "Subscription Renewal Reminder",
    content: "Your subscription is about to expire on {{expiry_date}}. Renew now to continue enjoying {{service}}.",
    language: "en",
    template_type: "transactional",
    tags: ["renewal", "subscription", "reminder"],
    type: "sms",
  },
  {
    id: 6,
    title: "Appointment Reminder",
    content: "Reminder: Your appointment with {{doctor_name}} is scheduled for {{appointment_date}} at {{appointment_time}}.",
    language: "en",
    template_type: "service",
    tags: ["appointment", "reminder", "health"],
    type: "sms",
  },
  {
    id: 7,
    title: "Order Confirmation",
    content: "Your order #{{order_id}} has been successfully placed. We will notify you once it's shipped.",
    language: "en",
    template_type: "transactional",
    tags: ["order", "confirmation", "ecommerce"],
    type: "sms",
  },
  {
    id: 8,
    title: "Shipping Notification",
    content: "Your order #{{order_id}} has been shipped and is on its way. Track your shipment here: {{tracking_url}}.",
    language: "en",
    template_type: "transactional",
    tags: ["shipping", "order", "ecommerce"],
    type: "sms",
  },
  {
    id: 9,
    title: "Delivery Confirmation",
    content: "Your order #{{order_id}} has been delivered successfully. Thank you for shopping with us!",
    language: "en",
    template_type: "transactional",
    tags: ["delivery", "order", "ecommerce"],
    type: "sms",
  },
  {
    id: 10,
    title: "Exclusive Offer!",
    content: "Hurry! Get {{discount_percentage}}% off on your next purchase. Use code {{promo_code}} at checkout.",
    language: "en",
    template_type: "promotional",
    tags: ["promotion", "offer", "discount"],
    type: "sms",
  },
  {
    id: 11,
    title: "New Product Launch",
    content: "Exciting news! Introducing our latest product: {{product_name}}. Available now at {{price}}.",
    language: "en",
    template_type: "promotional",
    tags: ["product", "launch", "promotion"],
    type: "sms",
  },
  {
    id: 12,
    title: "Happy Birthday!",
    content: "Wishing you a very happy birthday, {{name}}! Enjoy a special discount of {{discount_percentage}}% off your next purchase.",
    language: "en",
    template_type: "promotional",
    tags: ["birthday", "offer", "promotion"],
    type: "sms",
  },
  {
    id: 13,
    title: "Survey Invitation",
    content: "We value your feedback! Please take a moment to fill out our survey and help us improve: {{survey_link}}.",
    language: "en",
    template_type: "engagement",
    tags: ["survey", "feedback", "engagement"],
    type: "sms",
  },
  {
    id: 14,
    title: "Event Invitation",
    content: "You're invited to our exclusive event! Join us on {{event_date}} at {{event_location}}. RSVP here: {{rsvp_link}}.",
    language: "en",
    template_type: "engagement",
    tags: ["event", "invitation", "engagement"],
    type: "sms",
  },
  {
    id: 15,
    title: "Feedback Request",
    content: "We'd love to hear from you! Please share your thoughts about our service: {{feedback_link}}.",
    language: "en",
    template_type: "engagement",
    tags: ["feedback", "service", "engagement"],
    type: "sms",
  },
  {
    id: 16,
    title: "Weekly Newsletter",
    content: "Check out this week's top stories! Read the latest updates here: {{newsletter_link}}.",
    language: "en",
    template_type: "engagement",
    tags: ["newsletter", "update", "engagement"],
    type: "sms",
  },
  {
    id: 17,
    title: "Limited Time Offer",
    content: "Hurry, time is running out! Get {{discount_percentage}}% off on all items. Offer ends in {{time_remaining}}.",
    language: "en",
    template_type: "promotional",
    tags: ["limited time", "offer", "discount"],
    type: "sms",
  },
  {
    id: 18,
    title: "Customer Support Update",
    content: "Your support request #{{ticket_id}} has been resolved. If you need further assistance, feel free to contact us.",
    language: "en",
    template_type: "service",
    tags: ["support", "update", "ticket"],
    type: "sms",
  },
  {
    id: 19,
    title: "Invoice Reminder",
    content: "This is a reminder that your invoice #{{invoice_id}} of {{amount}} is due on {{due_date}}. Please make your payment.",
    language: "en",
    template_type: "transactional",
    tags: ["invoice", "reminder", "payment"],
    type: "sms",
  },
  {
    id: 20,
    title: "Service Disruption Alert",
    content: "We are experiencing service disruptions in your area. We are working to resolve the issue as quickly as possible. Thank you for your patience.",
    language: "en",
    template_type: "service",
    tags: ["alert", "disruption", "service"],
    type: "sms",
  },
  {
    id: 21,
    title: "Two-Factor Authentication",
    content: "Your two-factor authentication code is {{auth_code}}. Please enter it to complete your login.",
    language: "en",
    template_type: "security",
    tags: ["2fa", "security", "login"],
    type: "sms",
  },
  {
    id: 22,
    title: "Weekly Sales Update",
    content: "Check out this week's best deals! Shop now and save big on {{top_items}}.",
    language: "en",
    template_type: "promotional",
    tags: ["sales", "discount", "weekly"],
    type: "sms",
  },
  {
    id: 23,
    title: "Shipping Delay Notification",
    content: "We're sorry, but your order #{{order_id}} has been delayed. We will notify you once it has shipped.",
    language: "en",
    template_type: "service",
    tags: ["shipping", "delay", "order"],
    type: "sms",
  },
  {
    id: 24,
    title: "Account Deactivation Warning",
    content: "Your account will be deactivated on {{deactivation_date}}. Please take action to avoid service disruption.",
    language: "en",
    template_type: "service",
    tags: ["account", "warning", "deactivation"],
    type: "sms",
  },
  {
    id: 25,
    title: "Payment Declined",
    content: "Your payment attempt of {{amount}} was declined. Please check your payment details and try again.",
    language: "en",
    template_type: "transactional",
    tags: ["payment", "decline", "transaction"],
    type: "sms",
  },
  {
    id: 26,
    title: "Welcome to Our Service",
    content: "Thank you for joining {{app_name}}! We are excited to have you. Explore our features now.",
    language: "en",
    template_type: "engagement",
    tags: ["welcome", "onboarding", "service"],
    type: "sms",
  },
  {
    id: 27,
    title: "Monthly Summary",
    content: "Here's your monthly summary of activities on {{app_name}}. Check it out: {{summary_link}}.",
    language: "en",
    template_type: "engagement",
    tags: ["monthly", "summary", "report"],
    type: "sms",
  },
  {
    id: 28,
    title: "Special Event Discount",
    content: "Join us for our special event and get {{discount_percentage}}% off your next purchase. Don't miss out!",
    language: "en",
    template_type: "promotional",
    tags: ["event", "discount", "promotion"],
    type: "sms",
  },
  {
    id: 29,
    title: "Order Cancellation",
    content: "We're sorry to inform you that your order #{{order_id}} has been canceled. Please contact us if you have any questions.",
    language: "en",
    template_type: "transactional",
    tags: ["order", "cancellation", "customer service"],
    type: "sms",
  },
  {
    id: 30,
    title: "Account Balance Alert",
    content: "Your current account balance is {{balance}}. Please ensure your balance is sufficient for your upcoming payments.",
    language: "en",
    template_type: "service",
    tags: ["balance", "alert", "finance"],
    type: "sms",
  },
  // Email Templates
  {
    id: 31,
    title: "Account Verification",
    subject: "Verify your email address",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #4CAF50;} .button{background-color: #4CAF50; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Account Verification</h1><p>Hi {{user_name}},</p><p>Thank you for signing up. Please verify your email address by clicking the button below:</p><a href='{{verification_link}}' class='button'>Verify Email</a><p>If you didn't sign up for this account, please ignore this email.</p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "security",
    tags: ["account", "verification"],
    type: "email",
  },
  {
    id: 32,
    title: "Password Reset",
    subject: "Reset your password",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #FF5733;} .button{background-color: #FF5733; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Password Reset Request</h1><p>Hi {{user_name}},</p><p>We received a request to reset your password. Click the button below to reset your password:</p><a href='{{reset_link}}' class='button'>Reset Password</a><p>If you didn't request a password reset, please ignore this email.</p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "security",
    tags: ["password", "reset"],
    type: "email",
  },
  {
    id: 33,
    title: "Order Confirmation",
    subject: "Your Order has been Confirmed",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #009688;} table{width: 100%; margin: 20px 0;} th{text-align: left;} .button{background-color: #009688; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Order Confirmation</h1><p>Hi {{user_name}},</p><p>Your order with the following details has been confirmed:</p><table><tr><th>Order ID:</th><td>{{order_id}}</td></tr><tr><th>Total:</th><td>{{order_total}}</td></tr><tr><th>Items:</th><td>{{order_items}}</td></tr></table><p>Thank you for shopping with us! Your order will be shipped soon. You can track your order here: <a href='{{order_tracking_link}}' class='button'>Track Order</a></p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "transactional",
    tags: ["order", "confirmation"],
    type: "email",
  },
  {
    id: 34,
    title: "Subscription Renewal Reminder",
    subject: "Reminder: Your Subscription is about to Expire",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #FF9800;} .button{background-color: #FF9800; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Subscription Renewal Reminder</h1><p>Hi {{user_name}},</p><p>Your subscription to {{service_name}} is about to expire on {{expiry_date}}. Please renew now to continue enjoying our services:</p><a href='{{renewal_link}}' class='button'>Renew Subscription</a><p>If you have any questions, feel free to contact us.</p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "reminder",
    tags: ["subscription", "renewal"],
    type: "email",
  },
  {
    id: 35,
    title: "Welcome to {{company_name}}",
    subject: "Welcome aboard, {{user_name}}!",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #2196F3;} .button{background-color: #2196F3; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Welcome to {{company_name}}!</h1><p>Hi {{user_name}},</p><p>We are excited to have you onboard. You can start by exploring our services. Click below to get started:</p><a href='{{getting_started_link}}' class='button'>Get Started</a><p>We hope you enjoy your experience with us!</p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "engagement",
    tags: ["welcome", "onboarding"],
    type: "email",
  },
  {
    id: 36,
    title: "Password Change Confirmation",
    subject: "Your password has been successfully changed",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #4CAF50;} .button{background-color: #4CAF50; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Password Change Confirmation</h1><p>Hi {{user_name}},</p><p>Your password has been successfully changed. If you did not make this change, please contact our support team immediately.</p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "security",
    tags: ["password", "change"],
    type: "email",
  },
  {
    id: 37,
    title: "Invoice Receipt",
    subject: "Your Invoice for {{order_id}}",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #009688;} table{width: 100%; margin: 20px 0;} th{text-align: left;} .button{background-color: #009688; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Your Invoice for Order {{order_id}}</h1><p>Hi {{user_name}},</p><p>Thank you for your purchase. Here is your invoice for the order:</p><table><tr><th>Order ID:</th><td>{{order_id}}</td></tr><tr><th>Total:</th><td>{{invoice_total}}</td></tr><tr><th>Date:</th><td>{{invoice_date}}</td></tr></table><p>You can download the full invoice using the link below:</p><a href='{{invoice_link}}' class='button'>Download Invoice</a><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "transactional",
    tags: ["invoice", "receipt"],
    type: "email",
  },
  {
    id: 38,
    title: "Product Shipment Confirmation",
    subject: "Your Order has been Shipped",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #2196F3;} table{width: 100%; margin: 20px 0;} th{text-align: left;} .button{background-color: #2196F3; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Your Order has been Shipped</h1><p>Hi {{user_name}},</p><p>Your order has been shipped. Here are the details:</p><table><tr><th>Order ID:</th><td>{{order_id}}</td></tr><tr><th>Tracking Number:</th><td>{{tracking_number}}</td></tr><tr><th>Estimated Delivery Date:</th><td>{{delivery_date}}</td></tr></table><p>Track your shipment here: <a href='{{tracking_link}}' class='button'>Track Shipment</a></p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "transactional",
    tags: ["shipment", "order"],
    type: "email",
  },
  {
    id: 39,
    title: "Thank You for Your Purchase",
    subject: "Thank you for your purchase, {{user_name}}!",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #FF5722;} .button{background-color: #FF5722; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Thank You for Your Purchase!</h1><p>Hi {{user_name}},</p><p>Thank you for shopping with us. Your order is now complete. We hope you enjoy your new items! If you have any questions, feel free to reach out to our support team.</p><a href='{{shop_link}}' class='button'>Continue Shopping</a><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "engagement",
    tags: ["thank you", "purchase"],
    type: "email",
  },
  {
    id: 40,
    title: "Discount Offer",
    subject: "Exclusive Discount Just for You!",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #FF9800;} .button{background-color: #FF9800; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Exclusive Discount Just for You!</h1><p>Hi {{user_name}},</p><p>We're offering you a special discount of {{discount_amount}} on your next purchase. Use the code below:</p><h2>{{discount_code}}</h2><p>Click the button below to start shopping now:</p><a href='{{discount_link}}' class='button'>Shop Now</a><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "promotional",
    tags: ["discount", "offer"],
    type: "email",
  },
  {
    id: 41,
    title: "Email Subscription Confirmation",
    subject: "Confirm your subscription",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #2196F3;} .button{background-color: #2196F3; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Confirm your Subscription</h1><p>Hi {{user_name}},</p><p>You're almost ready to receive our updates. Just confirm your email by clicking the button below:</p><a href='{{confirmation_link}}' class='button'>Confirm Subscription</a><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "engagement",
    tags: ["email", "subscription"],
    type: "email",
  },
  {
    id: 42,
    title: "New Feature Announcement",
    subject: "Exciting New Feature - Try it Now!",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #673AB7;} .button{background-color: #673AB7; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Exciting New Feature - Try it Now!</h1><p>Hi {{user_name}},</p><p>We've just launched a new feature you'll love! Check it out now:</p><a href='{{new_feature_link}}' class='button'>Try the New Feature</a><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "engagement",
    tags: ["feature", "announcement"],
    type: "email",
  },
  {
    id: 43,
    title: "Shipping Delay Notification",
    subject: "We're experiencing a delay with your shipment",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #F44336;} .button{background-color: #F44336; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Shipping Delay Notification</h1><p>Hi {{user_name}},</p><p>We regret to inform you that your order is delayed due to unforeseen circumstances. We are working to resolve the issue and will notify you once your order has shipped.</p><p>We sincerely apologize for the inconvenience and appreciate your understanding.</p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "transactional",
    tags: ["shipping", "delay"],
    type: "email",
  },
  {
    id: 44,
    title: "Unsubscription Confirmation",
    subject: "You have successfully unsubscribed",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #333;} .container{max-width: 600px; margin: 0 auto;} h1{color: #FF5722;} .button{background-color: #FF5722; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>You have successfully unsubscribed</h1><p>Hi {{user_name}},</p><p>You've successfully unsubscribed from our email list. We're sorry to see you go!</p><p>If you change your mind, you can always <a href='{{resubscribe_link}}' class='button'>Resubscribe</a>.</p><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "engagement",
    tags: ["unsubscription", "confirmation"],
    type: "email",
  },
  {
    id: 45,
    title: "Account Suspended",
    subject: "Your account has been temporarily suspended",
    content: "<html><head><style>body{font-family: Arial, sans-serif; padding: 20px; color: #FF9800;} .container{max-width: 600px; margin: 0 auto;} h1{color: #FF9800;} .button{background-color: #FF9800; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;} @media (max-width: 600px){.container{padding: 15px;}}</style></head><body><div class='container'><h1>Your account has been temporarily suspended</h1><p>Hi {{user_name}},</p><p>Your account has been temporarily suspended due to suspicious activity. Please review your account and contact support for assistance.</p><a href='{{support_link}}' class='button'>Contact Support</a><p>Best regards, <br>The {{company_name}} Team</p></div></body></html>",
    language: "en",
    template_type: "security",
    tags: ["account", "suspended"],
    type: "email",
  },
]

export function getAllTemplates(): Template[] {
  return templates
}

export function getTemplateById(id: number): Template | undefined {
  return templates.find((template) => template.id === id)
}